# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: docs.nucleos.rocks
  description: 📖 Documentation for all nucleos projects
  homepage: https://docs.nucleos.rocks
  topics: documentation

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Lint / DOCtor-RST"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
